---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-helm
  namespace: vault
spec:
  chart:
    spec:
      chart: vault-helm
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault

  interval: 1m0s
  values:
    server:
      affinity: ""
      ha:
        enabled: true
        raft: 
          enabled: true



  