---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metrics-server
      version: 3.8.3
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system

  interval: 1m0s
  values:
    containerPort: 10250




  