apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: metrics-server
      version: "6.2.9"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    containerPorts: 
      https: 10250
    command:
      - metrics-server
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP    
      


  