creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: '^(data|stringData)$'
    age: age1acu8hvgcgy3r8vnnpe22lfy6jfs3h2c3wu0thp93vpu27u7p2yaqscf0c9
    kms: arn:aws:kms:us-east-1:052776272001:key/f1befbbe-1554-4d23-9adc-27ad82256440
