apiVersion: v1
data:
    password: ENC[AES256_GCM,data:AgEVKAgVV6JckE/C,iv:lbEvJODH2YTCrqg5h3qNmDYEkZpcKmFu6JTbHcyjb4o=,tag:zpElnNZ5zhx1tQTIqlytaw==,type:str]
    user: ENC[AES256_GCM,data:6ozlZMwYwPE=,iv:vLIfVBlGoRzsJubsZs5SeAb1obyTYX0KocIrEq6G20A=,tag:khpZQEi4YcgsFFRERmh4tA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: flux-system
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:052776272001:key/525e545d-57b6-483c-9229-1cdd1958db44
          created_at: "2023-03-23T14:32:53Z"
          enc: AQICAHg1060XnCwnjOsJlHXF3OQHxelr7aPTUsK+OHRz2oS7MQFdhPxT432P+w+lWw1kKWLjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOr4lsp2cGktUMPj+AgEQgDs9/o+7rC5HjYFdOzmOn21WrILZvhnwU6EKFOIh3H8G/2HE6lN04z5+tVYEOQ6UY9N8p2oQxIU//BVang==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1acu8hvgcgy3r8vnnpe22lfy6jfs3h2c3wu0thp93vpu27u7p2yaqscf0c9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcTZBaUx6bGVYZUwzZlds
            cGRtR1h6OXNjUjdnMVZHRTlLRDFrNGtPdjNNCjJ4YnVlL0lNTEpKUnZzY1MyYSty
            eVdkSDJmczBNZHVQQklCd0FmSktwTEEKLS0tIGg2THNZdVNORUJXcGR2eWozR0ZG
            RXlXd0F2UktxOC8wNlJGK2JJcnRNb0EK5g81JQJanY+13287y4EiwBd8hjaUeJ1k
            XOkSUpW44nw0xrGZ5sGm7fIYqdD8/F0vlDuDGCPGyuF5CuDnbillWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T14:32:53Z"
    mac: ENC[AES256_GCM,data:6ddYB1TvhCAZ3HUKCUV5z++FVaA9EOarxshBqNZai3vgvY3JXgbZKiYgdhDM40Dua+FRRIwL3quJ34Cr8f5fF1EK1Q+4yxc78Kk0zo7lo+Q6i/cnL4uehbSRbmCHblAcYsA6yKuGZQasugzNZLEYdr928W50v65+iWKLMLnzmsI=,iv:Y8/odsuax90zi4LWbcDlNdC6aXcwOz/fw5bGSr20HuM=,tag:iiI/HAE+kf6W8rkylUFyUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
